import type { Upgrade } from '../types/index';

export const UPGRADES: Upgrade[] = [
  {
    id: 1,
    name: "Upgrade your GPU",
    description: "Buy the newest consumer graphics card to boost your training rate and improve your model",
    category: "production",
    cost: 500,
    moneyPerSecond: 25,
    pollutionPerSecond: 15
  },
  {
    id: 2,
    name: "A New PC",
    description: "Buy a brand new top-of-the-range PC to further increase your training rate and improve your model",
    category: "production",
    cost: 3000,
    moneyPerSecond: 150,
    pollutionPerSecond: 85,
  },
  {
    id: 3,
    name: "Local Server Rack",
    description: "A new rack of local servers to further increase your training capability.",
    category: "production",
    cost: 6500,
    moneyPerSecond: 350,
    pollutionPerSecond: 175
  },
  {
    id: 4,
    name: "Build a New Datacentre",
    description: "The pinnacle in AI hardware, a brand new server farm to host your models for the masses",
    category: "production",
    cost: 12000,
    moneyPerSecond: 600,
    pollutionPerSecond: 500,
  },
  {
    id: 5,
    name: "Add Image Generation Functionality",
    description: "Expand your AI service by introducing an image generation model",
    category: "production",
    cost: 15000,
    moneyPerSecond: 1000,
    pollutionPerSecond: 750
  },

  // -------------------------------------------------------------
  // PERCEPTION UPGRADES (Bad)
  // -------------------------------------------------------------
 {
    id: 6,
    name: "Unsubstantiated AI Climate Claims",
    description: "Market the green benefits of your AI products without any real evidence or lifecycle analysis to back it up.",
    category: "production",
    cost: 1500,
    perceptionImpact: 5,
    educationalMessage: "AI companies have frequently made bold claims about their products' potential to reduce emissions, such as optimizing energy use or improving supply chain efficiency. However, these claims are often based on theoretical models without any real-world testing or lifecycle analysis, and they ignore the massive emissions generated by training and running large AI models.",
    realWorldEvidence: "Only 26% of AI CLimate claims cite reseach and 36% provide no evidence at all, according to Climate non-profit Beyong Fossil Fuels.",
    source: "Euronews",
    sourceUrl: "https://www.euronews.com/next/2026/02/17/ai-greenwashing-most-of-big-techs-ai-climate-promises-fall-flat-study-finds"
  },
  {
    id: 7,
    name: "Misleading Progress Narative",
    description: "Use some creative accounting to show a 'decrease' in datacentre emissions.",
    category: "perception",
    cost: 2500,
    perceptionImpact: 10,
    educationalMessage: "Companies often report 'emissions intensity' (emissions per unit of production) instead of absolute emissions, and abuse carbon credits, allowing them to claim progress even as their total carbon footprint skyrockets.",
    realWorldEvidence: "Google's 2025 Sustainablity Report noted a 17% reduction in datacentre emissions desipte the fact that their total electricity usage increased by 23%, this is only possible due to clever climate accounting",
    source: "Google's 2025 Sustainablity Report",
    sourceUrl: "https://www.gstatic.com/gumdrop/sustainability/google-2025-environmental-report.pdf"
  },
  {
    id: 8,
    name: "Enable Others to 'Reduce' Emissions",
    description: "Boast about the climate benefits your products haev given to customers without any real evidence.",
    category: "perception",
    cost: 5000,
    perceptionImpact: 15,
    educationalMessage: "Tech companies are more than happy to claim when their products help sustainability. Unfortunately they also love to oversell it.",
    realWorldEvidence: "In 2025, Google claimed that their products helped to reduce emissions by over 26 million tons of CO₂ however, half of this figure originates from numbers reported by corporate partners who use Google Earth Pro. A dubious claim at best.",
    source: "Google's 2025 Sustainablity report",
    sourceUrl: "https://sustainability.google/stories/how-google-earth-pro-helps-clean-energy-development/"
  },
  

  
  // -------------------------------------------------------------
  // PERCEPTION UPGRADES (Good)
  // -------------------------------------------------------------

  // TODO: Add good upgrades here linked to SSE course material
];
